name: filevo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.0.7
  fl_chart: ^1.1.1
  icons_plus: ^4.0.0
  font_awesome_flutter: ^10.7.0
  device_preview: ^1.3.1
  stylish_bottom_bar: ^1.1.1
  flutterzilla_fixed_grid: ^0.0.4
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.0
  http: ^1.1.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_verification_code_field: ^1.2.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.10.5
  flutter_pdfview: ^1.2.5
  video_player: ^2.8.1
  path_provider: ^2.0.15
  chewie: ^1.4.0
  photo_view: ^0.15.0
  pdf: ^3.11.1
  audioplayers: ^6.5.1
  url_launcher: ^6.1.11
  open_filex: ^4.3.3
  share_plus: ^10.1.2
  cached_network_image: ^3.4.1
  video_thumbnail: ^0.5.6
  permission_handler: ^12.0.1
  flutter_file_dialog: ^3.0.2
  saf: ^1.0.4
  image_picker: ^1.1.2
  pro_image_editor: ^11.14.1
  pro_video_editor: ^0.4.0
  video_editor: ^3.0.0
  speech_to_text: ^7.0.0
  # ffmpeg_kit_flutter_min: 6.0.3  # Temporarily disabled - package is discontinued and Android artifacts are not available
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  flutter_windowmanager: ^0.2.0
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
